export const languages = {
  fr: {
    dropdownMenu: {
      companyList: 'Liste des entreprises',
      specialities: 'Spécialités',
      defaultFilter: 'Toutes',
      dltq: "Développement Logiciel, Tests et Qualité",
      iabd: "IA & Big Data"
    },
    addCompanyForm: {
      addCompany: "Ajouter une entreprise",
      reviewTitle: "Vérifier la proposition",
      schoolSpeciality: "Spécialité de l'école",
      selectSpeciality: "-- Sélectionner une spécialité --",
      dltq: "Développement Logiciel, Tests et Qualité",
      iabd: "IA & Big Data",
      companyName: "Nom",
      companyWebsite: "Site web de l'entreprise",
      companyState: "Pays",
      selectCompanyState: "-- Sélectionner un pays --",
      errorCompanyStateNotCoherent: "Le pays renseigné n'est pas cohérent avec l'adresse renseignée. Merci de mettre : ",
      companyAddress: "Adresse",
      companyCity: "Ville",
      companyPC: "Code Postal",
      mapPlaceHint: "Cliquez sur la carte pour placer le point, ou remplissez l'adresse pour une recherche automatique.",
      mapAdjustHint: "Glissez le repère ou cliquez ailleurs sur la carte pour ajuster précisément son emplacement.",
      addCompanyButton: "Ajouter l'entreprise",
      validateButton: "Valider",
      rejectButton: "Refuser",
      closeButton: "Fermer",
      pendingSubmittedTitle: "Proposition envoyée",
      pendingSubmittedText: "Votre entreprise a été soumise et sera visible sur la carte après validation par un administrateur.",
      step1Label: "Entreprise",
      step2Label: "Contact",
      step3Label: "Mission",
      step4Label: "Avis",
      stepErrorCompany: "Merci de compléter tous les champs de l'entreprise et de placer un point sur la carte.",
      stepErrorWebsite: "Le site web renseigné n'est pas une URL valide.",
      stepErrorContacts: "Merci de renseigner nom, prénom, rôle et un email valide pour chaque contact.",
      stepErrorMission: "Merci de décrire brièvement la mission effectuée.",
      stepErrorGeneric: "Certaines informations sont invalides ou incomplètes.",
      contactsHint: "Personne(s) à qui envoyer un CV ou une lettre de motivation pour ce stage/alternance.",
      contactN: "Contact",
      removeContact: "Retirer ce contact",
      addContact: "+ Ajouter un autre contact",
      contactFirstName: "Prénom",
      contactLastName: "Nom",
      contactRole: "Rôle / Poste",
      contactEmail: "Email",
      contactPhone: "Téléphone",
      contactsPrivacyNote: "Chaque contact recevra un email l'informant que ses coordonnées sont visibles sur le site, avec la possibilité de les masquer.",
      missionLabel: "Mission effectuée",
      missionHint: "Décrivez rapidement ce que vous avez fait pendant votre stage/alternance.",
      reviewHint: "Facultatif : partagez votre avis sur cette entreprise pour aider les futurs étudiants.",
      reviewRatingLabel: "Recommandez-vous cette entreprise ?",
      reviewCommentLabel: "Votre avis",
      previousButton: "Précédent",
      nextButton: "Suivant"
    },
    companyItem: {
      companyCity: "Ville",
      companyState: "Pays",
      companyPC: "Code Postal",
      clickForDetails: "Cliquez pour plus d'informations"
    },
    companyInformations: {
      missionTitle: "Mission",
      reviewTitle: "Avis",
      contactsTitle: "Contact",
      loadingContacts: "Chargement des contacts...",
      noContacts: "Aucun contact renseigné.",
      contactHidden: "Cette personne a choisi de masquer ses informations personnelles."
    },
    hideContact: {
      title: "Masquer mes informations",
      loading: "Vérification du lien...",
      intro: "Vos coordonnées sont actuellement visibles sur Find My Company en tant que contact pour",
      warning: "En confirmant, votre nom, prénom, rôle, email et téléphone seront définitivement retirés du site.",
      confirmButton: "Masquer mes informations",
      alreadyHidden: "Vos informations ont déjà été masquées.",
      done: "Vos informations personnelles ont été retirées du site.",
      invalid: "Ce lien est invalide ou a expiré.",
      error: "Une erreur est survenue, merci de réessayer plus tard.",
      backToSite: "← Retour au site"
    },
    login: {
      title: "Connexion",
      email: "Email",
      password: "Mot de passe",
      submit: "Se connecter",
      error: "Identifiants invalides.",
      loggedInAs: "Connecté en tant qu'administrateur",
      logout: "Se déconnecter"
    },
    pendingCompanies: {
      title: "Entreprises en attente de validation",
      empty: "Aucune entreprise en attente.",
      review: "Modifier / Valider",
      reject: "Refuser",
      confirmReject: "Refuser définitivement cette proposition ?",
      back: "Retour à la liste"
    },
    mapLayers: {
      standard: "Standard",
      satellite: "Satellite",
      dark: "Sombre",
      terrain: "Relief"
    }
  },
  en: {
    dropdownMenu: {
      companyList: 'Company List',
      specialities: 'Specialities',
      defaultFilter: 'All',
      dltq: "Software Development, Testing and Quality",
      iabd: "AI & Big Data"
    },
    addCompanyForm: {
      addCompany: "Add a company",
      reviewTitle: "Review submission",
      schoolSpeciality: "School speciality",
      selectSpeciality: "-- Select a speciality --",
      dltq: "Software Development, Testing and Quality",
      iabd: "AI & Big Data",
      companyName: "Name",
      companyWebsite: "Company website",
      companyState: "Country",
      selectCompanyState: "-- Select a country --",
      errorCompanyStateNotCoherent: "The country provided is not coherent with the address provided. Please use: ",
      companyAddress: "Address",
      companyCity: "City",
      companyPC: "Postal Code",
      mapPlaceHint: "Click on the map to place the point, or fill in the address for an automatic search.",
      mapAdjustHint: "Drag the pin or click elsewhere on the map to fine-tune its location.",
      addCompanyButton: "Add company",
      validateButton: "Approve",
      rejectButton: "Reject",
      closeButton: "Close",
      pendingSubmittedTitle: "Submission sent",
      pendingSubmittedText: "Your company was submitted and will appear on the map once an administrator approves it.",
      step1Label: "Company",
      step2Label: "Contact",
      step3Label: "Mission",
      step4Label: "Review",
      stepErrorCompany: "Please fill in all company fields and place a point on the map.",
      stepErrorWebsite: "The website provided is not a valid URL.",
      stepErrorContacts: "Please fill in first name, last name, role and a valid email for each contact.",
      stepErrorMission: "Please briefly describe the mission you carried out.",
      stepErrorGeneric: "Some information is invalid or incomplete.",
      contactsHint: "Person(s) to send a CV or cover letter to for this internship/apprenticeship.",
      contactN: "Contact",
      removeContact: "Remove this contact",
      addContact: "+ Add another contact",
      contactFirstName: "First name",
      contactLastName: "Last name",
      contactRole: "Role / Position",
      contactEmail: "Email",
      contactPhone: "Phone",
      contactsPrivacyNote: "Each contact will receive an email letting them know their details are visible on the site, with the option to hide them.",
      missionLabel: "Mission carried out",
      missionHint: "Briefly describe what you did during your internship/apprenticeship.",
      reviewHint: "Optional: share your opinion on this company to help future students.",
      reviewRatingLabel: "Would you recommend this company?",
      reviewCommentLabel: "Your review",
      previousButton: "Previous",
      nextButton: "Next"
    },
    companyItem: {
      companyCity: "City",
      companyState: "Country",
      companyPC: "Postal Code",
      clickForDetails: "Click for more details"
    },
    companyInformations: {
      missionTitle: "Mission",
      reviewTitle: "Review",
      contactsTitle: "Contact",
      loadingContacts: "Loading contacts...",
      noContacts: "No contact provided.",
      contactHidden: "This person chose to hide their personal information."
    },
    hideContact: {
      title: "Hide my information",
      loading: "Checking the link...",
      intro: "Your details are currently visible on Find My Company as a contact for",
      warning: "By confirming, your name, role, email and phone number will be permanently removed from the site.",
      confirmButton: "Hide my information",
      alreadyHidden: "Your information has already been hidden.",
      done: "Your personal information has been removed from the site.",
      invalid: "This link is invalid or has expired.",
      error: "Something went wrong, please try again later.",
      backToSite: "← Back to site"
    },
    login: {
      title: "Login",
      email: "Email",
      password: "Password",
      submit: "Log in",
      error: "Invalid credentials.",
      loggedInAs: "Logged in as administrator",
      logout: "Log out"
    },
    pendingCompanies: {
      title: "Companies awaiting approval",
      empty: "No pending companies.",
      review: "Edit / Approve",
      reject: "Reject",
      confirmReject: "Permanently reject this submission?",
      back: "Back to list"
    },
    mapLayers: {
      standard: "Standard",
      satellite: "Satellite",
      dark: "Dark",
      terrain: "Terrain"
    }
  }
}
